version: '3'
services: 
  mongo:
  container-name: mongo-container
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - clean-ts-api
  api:
    container_name: api-container
    build: .
    restart: always
    image: clean-node-api
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-ts-api/dist
    ports:
      - "5050:5050"
    links:
      - mongo


